### ISSUE TITLE
Json results

### ISSUE THREAD

**Issue by junquajc** [capioai/API-Documentation#11]
Unless I misunterdoord it looks like the examples of results provided do not follow the structure of the results outlined above and copied hereafter

result : main ASR result JSON array objectalternative: n-best results in an array confidence: sentence level confidence score (float)transcript: recognized word sentence (string)(optional) timestamp: word level timestamp in an array of {word, start_time, end_time}(optional) word_confidence: word level confidence in array of {word, confidence}stability: sentence stability provided for a partial result indicating how likely the result is to change (flow)final: end of sentence recognition (boolean - true for final results and false for partial results)result_index: index of this sentence since start of transaction (int)

**Comment by glory791days** [comment]
The result may be changed due to updated implementation. I will check it.

**Comment by glory791days** [comment]
Actually the structure has been changed. I updated to what I observed today.
